### ISSUE TITLE
Style Guide: simplified version 

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/mozfest-design-2017#39]
Please create a simplified version of the style guide to share with space wranglers and, later in September, session facilitators.

**Comment by sabrinang** [comment]
I made a short simplified version of the style guide in the format of a gslides presentation: https://docs.google.com/presentation/d/1E7k4LHwab2QsdUereRBN3ePJvRC0ex2wwJCKBX3jKn4/edit?usp=sharing

The end of it is still WIP (mainly working out colours in wayfinding) but the main thing here is a downloadable link for the space icons down in the speaker notes section.

**Comment by sabrinang** [comment]
Some feedback I got and thoughts after sharing this on the call today:

What is the expectation with wranglers/facilitators and design? Maybe we should only share a limited amount of stuff because by sharing too many assets, it may create an unexpected burden/pressure that they are expected to design their own stuff this year (and they already have lots on their plates).

Also, I’m getting a feeling that a lot of unofficial things can be produced to look official or the odd in-between with the entire system available. This is only a concern from the standpoint of how our attendees understand wayfinding and how they can differentiate what is official and what is not. How do we moderate that understanding of our brand and the perception of quality?

@Saallen @edrushka Any thoughts on this?

**Comment by xmatthewx** [comment]
👍 good idea to give them a limited set of things, maybe icons, gray textures ... but reserve logo, bright colors for official stuff. some people might butcher the elements and blur the line with wayfinding and other official stuff.

**Comment by Saallen** [comment]
@sabrinang , I think Matthew is right, give them assets that you dont mind them remixing or using.
There is no expectation on wranglers for design assest- they do however have budget to buy props, cool swag or bits to decorate their space. This can be a remix of you style guide or just filling their space with disco balls!

**Comment by sabrinang** [comment]
I simplified the simple style guide: https://docs.google.com/presentation/d/1E7k4LHwab2QsdUereRBN3ePJvRC0ex2wwJCKBX3jKn4/edit?usp=sharing
Which includes brand (logo/wordmark/lockup), cube pattern and motifs, zilla slab/highlight typeface, space icon and colour swatch. I removed the extras to keep this limited (which can be found in the extended guide for contractors and designers).
